<?php

namespace App\Support;

final class SystemTextCatalog
{
    public static function items(): array
    {
        return [
            ['key' => 'app.brand.title', 'group' => '后台框架', 'label' => '侧栏主标题', 'default_value' => '科技项目管理', 'sort_order' => 10],
            ['key' => 'app.brand.subtitle', 'group' => '后台框架', 'label' => '侧栏副标题', 'default_value' => '公共服务后台', 'sort_order' => 20],
            ['key' => 'app.topbar.subtitle', 'group' => '后台框架', 'label' => '顶部系统名称', 'default_value' => '阿拉善盟科技计划项目管理信息系统', 'sort_order' => 30],
            ['key' => 'app.account.default_name', 'group' => '后台框架', 'label' => '当前账号默认名', 'default_value' => '当前账号', 'sort_order' => 40],
            ['key' => 'app.message.tooltip', 'group' => '后台框架', 'label' => '站内消息提示', 'default_value' => '站内消息', 'sort_order' => 50],
            ['key' => 'app.profile', 'group' => '后台框架', 'label' => '个人资料', 'default_value' => '个人资料', 'sort_order' => 60],
            ['key' => 'app.change_password', 'group' => '后台框架', 'label' => '修改密码', 'default_value' => '修改密码', 'sort_order' => 70],
            ['key' => 'app.switch_account', 'group' => '后台框架', 'label' => '切换账号', 'default_value' => '切换账号', 'sort_order' => 80],
            ['key' => 'app.logout', 'group' => '后台框架', 'label' => '退出登录', 'default_value' => '退出登录', 'sort_order' => 90],

            ['key' => 'menu.dashboard', 'group' => '菜单', 'label' => '运行概览菜单', 'default_value' => '运行概览', 'sort_order' => 100],
            ['key' => 'menu.projects', 'group' => '菜单', 'label' => '项目申报菜单', 'default_value' => '项目申报', 'sort_order' => 110],
            ['key' => 'menu.application_batches', 'group' => '菜单', 'label' => '申报批次菜单', 'default_value' => '申报批次', 'sort_order' => 120],
            ['key' => 'menu.acceptance', 'group' => '菜单', 'label' => '验收管理菜单', 'default_value' => '验收管理', 'sort_order' => 130],
            ['key' => 'menu.acceptance_admin', 'group' => '菜单', 'label' => '验收管理管理员菜单', 'default_value' => '验收管理', 'sort_order' => 140],
            ['key' => 'menu.lifecycle', 'group' => '菜单', 'label' => '全周期管理菜单', 'default_value' => '全周期管理', 'sort_order' => 150],
            ['key' => 'menu.units', 'group' => '菜单', 'label' => '单位管理菜单', 'default_value' => '单位管理', 'sort_order' => 160],
            ['key' => 'menu.users', 'group' => '菜单', 'label' => '账号管理菜单', 'default_value' => '账号管理', 'sort_order' => 170],
            ['key' => 'menu.unit_profile', 'group' => '菜单', 'label' => '单位资料菜单', 'default_value' => '单位资料', 'sort_order' => 180],
            ['key' => 'menu.reviews', 'group' => '菜单', 'label' => '审核任务菜单', 'default_value' => '审核任务', 'sort_order' => 190],
            ['key' => 'menu.messages', 'group' => '菜单', 'label' => '站内消息菜单', 'default_value' => '站内消息', 'sort_order' => 200],
            ['key' => 'menu.public_home', 'group' => '菜单', 'label' => '首页管理菜单', 'default_value' => '首页管理', 'sort_order' => 210],
            ['key' => 'menu.mail_center', 'group' => '菜单', 'label' => '邮件中心菜单', 'default_value' => '邮件中心', 'sort_order' => 220],
            ['key' => 'menu.roles', 'group' => '菜单', 'label' => '角色权限菜单', 'default_value' => '角色权限', 'sort_order' => 230],
            ['key' => 'menu.security', 'group' => '菜单', 'label' => '安全中心菜单', 'default_value' => '安全中心', 'sort_order' => 240],
            ['key' => 'menu.dictionary_items', 'group' => '菜单', 'label' => '数据字典菜单', 'default_value' => '数据字典', 'sort_order' => 250],
            ['key' => 'menu.system_texts', 'group' => '菜单', 'label' => '系统文案菜单', 'default_value' => '系统文案', 'sort_order' => 260],
            ['key' => 'menu.settings', 'group' => '菜单', 'label' => '系统配置菜单', 'default_value' => '系统配置', 'sort_order' => 270],
            ['key' => 'menu.migration', 'group' => '菜单', 'label' => '迁移准备菜单', 'default_value' => '迁移准备', 'sort_order' => 280],
            ['key' => 'menu.operation_logs', 'group' => '菜单', 'label' => '操作日志菜单', 'default_value' => '操作日志', 'sort_order' => 290],

            ['key' => 'page.dashboard.title', 'group' => '页面标题', 'label' => '运行概览标题', 'default_value' => '运行概览', 'sort_order' => 300],
            ['key' => 'page.projects.title', 'group' => '页面标题', 'label' => '项目申报标题', 'default_value' => '项目申报', 'sort_order' => 310],
            ['key' => 'page.application_batches.title', 'group' => '页面标题', 'label' => '申报批次标题', 'default_value' => '申报批次', 'sort_order' => 320],
            ['key' => 'page.acceptance.title', 'group' => '页面标题', 'label' => '验收管理标题', 'default_value' => '验收管理', 'sort_order' => 330],
            ['key' => 'page.lifecycle.title', 'group' => '页面标题', 'label' => '全周期管理标题', 'default_value' => '全周期管理', 'sort_order' => 340],
            ['key' => 'page.units.title', 'group' => '页面标题', 'label' => '单位管理标题', 'default_value' => '单位管理', 'sort_order' => 350],
            ['key' => 'page.users.title', 'group' => '页面标题', 'label' => '账号管理标题', 'default_value' => '账号管理', 'sort_order' => 360],
            ['key' => 'page.unit_profile.title', 'group' => '页面标题', 'label' => '单位资料标题', 'default_value' => '单位资料', 'sort_order' => 370],
            ['key' => 'page.reviews.title', 'group' => '页面标题', 'label' => '审核任务标题', 'default_value' => '审核任务', 'sort_order' => 380],
            ['key' => 'page.messages.title', 'group' => '页面标题', 'label' => '站内消息标题', 'default_value' => '站内消息', 'sort_order' => 390],
            ['key' => 'page.public_home.title', 'group' => '页面标题', 'label' => '首页管理标题', 'default_value' => '首页管理', 'sort_order' => 400],
            ['key' => 'page.mail_center.title', 'group' => '页面标题', 'label' => '邮件中心标题', 'default_value' => '邮件中心', 'sort_order' => 410],
            ['key' => 'page.roles.title', 'group' => '页面标题', 'label' => '角色权限标题', 'default_value' => '角色权限', 'sort_order' => 420],
            ['key' => 'page.security.title', 'group' => '页面标题', 'label' => '安全中心标题', 'default_value' => '安全中心', 'sort_order' => 430],
            ['key' => 'page.dictionary_items.title', 'group' => '页面标题', 'label' => '数据字典标题', 'default_value' => '数据字典', 'sort_order' => 440],
            ['key' => 'page.system_texts.title', 'group' => '页面标题', 'label' => '系统文案标题', 'default_value' => '系统文案', 'sort_order' => 450],
            ['key' => 'page.settings.title', 'group' => '页面标题', 'label' => '系统配置标题', 'default_value' => '系统配置', 'sort_order' => 460],
            ['key' => 'page.migration.title', 'group' => '页面标题', 'label' => '迁移准备标题', 'default_value' => '迁移准备', 'sort_order' => 470],
            ['key' => 'page.operation_logs.title', 'group' => '页面标题', 'label' => '操作日志标题', 'default_value' => '操作日志', 'sort_order' => 480],

            ['key' => 'dashboard.workflow.title', 'group' => '流程说明', 'label' => '流程图标题', 'default_value' => '科研项目申报与管理全流程', 'sort_order' => 500],
            ['key' => 'dashboard.workflow.description', 'group' => '流程说明', 'label' => '流程图说明', 'default_value' => '按业务全生命周期展示，并标明系统内办理和线下办理节点', 'sort_order' => 510],
            ['key' => 'dashboard.workflow.system', 'group' => '流程说明', 'label' => '系统内办理图例', 'default_value' => '系统内办理', 'sort_order' => 520],
            ['key' => 'dashboard.workflow.offline', 'group' => '流程说明', 'label' => '线下办理图例', 'default_value' => '线下办理/人工决策', 'sort_order' => 530],
            ['key' => 'dashboard.workflow.online_note', 'group' => '流程说明', 'label' => '已上线说明', 'default_value' => '已上线：注册审核、批次申报、附件、分级审核、合同任务书、实施进展、整改闭环、专家认证、验收和延期。', 'sort_order' => 540],
            ['key' => 'dashboard.workflow.offline_note', 'group' => '流程说明', 'label' => '线下说明', 'default_value' => '线下：局领导办公会、经费拨付、部分立项决策仍按现实业务办理。', 'sort_order' => 550],
            ['key' => 'dashboard.workflow.tab.lifecycle', 'group' => '流程说明', 'label' => '全生命周期 Tab', 'default_value' => '业务全生命周期', 'sort_order' => 560],
            ['key' => 'dashboard.workflow.tab.application', 'group' => '流程说明', 'label' => '申报审核 Tab', 'default_value' => '系统申报审核', 'sort_order' => 570],
            ['key' => 'dashboard.workflow.tab.acceptance', 'group' => '流程说明', 'label' => '验收审核 Tab', 'default_value' => '系统验收审核', 'sort_order' => 580],
            ['key' => 'workflow.lane.unit-life.title', 'group' => '流程图节点', 'label' => '全生命周期-申报单位', 'default_value' => '申报单位', 'sort_order' => 1000],
            ['key' => 'workflow.lane.unit-life.owner', 'group' => '流程图节点', 'label' => '全生命周期-申报单位责任主体', 'default_value' => '项目承担单位', 'sort_order' => 1001],
            ['key' => 'workflow.step.unit-life.01.title', 'group' => '流程图节点', 'label' => '单位注册与审核标题', 'default_value' => '单位注册与审核', 'sort_order' => 1002],
            ['key' => 'workflow.step.unit-life.01.body', 'group' => '流程图节点', 'label' => '单位注册与审核说明', 'default_value' => '单位注册后待审核，启用单位和账号后才能申报。', 'sort_order' => 1003],
            ['key' => 'workflow.step.unit-life.02.title', 'group' => '流程图节点', 'label' => '项目申报材料标题', 'default_value' => '项目申报材料', 'sort_order' => 1004],
            ['key' => 'workflow.step.unit-life.02.body', 'group' => '流程图节点', 'label' => '项目申报材料说明', 'default_value' => '选择开放批次，填写项目资料并上传申报附件。', 'sort_order' => 1005],
            ['key' => 'workflow.step.unit-life.03.title', 'group' => '流程图节点', 'label' => '补充完善标题', 'default_value' => '补充完善', 'sort_order' => 1006],
            ['key' => 'workflow.step.unit-life.03.body', 'group' => '流程图节点', 'label' => '补充完善说明', 'default_value' => '审核退回后补正材料，可再次提交进入审核。', 'sort_order' => 1007],
            ['key' => 'workflow.step.unit-life.08.title', 'group' => '流程图节点', 'label' => '合同任务书标题', 'default_value' => '合同任务书', 'sort_order' => 1008],
            ['key' => 'workflow.step.unit-life.08.body', 'group' => '流程图节点', 'label' => '合同任务书说明', 'default_value' => '任务书填写、提交和管理员审核已纳入全周期管理。', 'sort_order' => 1009],
            ['key' => 'workflow.step.unit-life.10.title', 'group' => '流程图节点', 'label' => '项目实施标题', 'default_value' => '项目实施', 'sort_order' => 1010],
            ['key' => 'workflow.step.unit-life.10.body', 'group' => '流程图节点', 'label' => '项目实施说明', 'default_value' => '单位可提交阶段进展、存在问题和下一步计划，管理员确认或退回。', 'sort_order' => 1011],
            ['key' => 'workflow.step.unit-life.11.title', 'group' => '流程图节点', 'label' => '验收材料与延期标题', 'default_value' => '验收材料与延期', 'sort_order' => 1012],
            ['key' => 'workflow.step.unit-life.11.body', 'group' => '流程图节点', 'label' => '验收材料与延期说明', 'default_value' => '提交验收材料，必要时发起延期申请。', 'sort_order' => 1013],
            ['key' => 'workflow.step.unit-life.14.title', 'group' => '流程图节点', 'label' => '整改闭环标题', 'default_value' => '整改闭环', 'sort_order' => 1014],
            ['key' => 'workflow.step.unit-life.14.body', 'group' => '流程图节点', 'label' => '整改闭环说明', 'default_value' => '管理员发起整改要求，单位提交整改说明，管理员审核闭环。', 'sort_order' => 1015],
            ['key' => 'workflow.lane.county-life.title', 'group' => '流程图节点', 'label' => '全生命周期-归口管理单位', 'default_value' => '归口管理单位', 'sort_order' => 1016],
            ['key' => 'workflow.lane.county-life.owner', 'group' => '流程图节点', 'label' => '全生命周期-归口责任主体', 'default_value' => '区县/归口', 'sort_order' => 1017],
            ['key' => 'workflow.step.county-life.04.title', 'group' => '流程图节点', 'label' => '归口初审标题', 'default_value' => '归口初审', 'sort_order' => 1018],
            ['key' => 'workflow.step.county-life.04.body', 'group' => '流程图节点', 'label' => '归口初审说明', 'default_value' => '对应旧流程“择优初审”，通过后流转主管部门。', 'sort_order' => 1019],
            ['key' => 'workflow.step.county-life.12.title', 'group' => '流程图节点', 'label' => '验收初审标题', 'default_value' => '验收初审', 'sort_order' => 1020],
            ['key' => 'workflow.step.county-life.12.body', 'group' => '流程图节点', 'label' => '验收初审说明', 'default_value' => '对验收材料完整性和属地意见进行初审。', 'sort_order' => 1021],
            ['key' => 'workflow.lane.department-life.title', 'group' => '流程图节点', 'label' => '全生命周期-科技局/主管部门', 'default_value' => '科技局/主管部门', 'sort_order' => 1022],
            ['key' => 'workflow.lane.department-life.owner', 'group' => '流程图节点', 'label' => '全生命周期-业务科室', 'default_value' => '业务科室', 'sort_order' => 1023],
            ['key' => 'workflow.step.department-life.05.title', 'group' => '流程图节点', 'label' => '形式审查标题', 'default_value' => '形式审查', 'sort_order' => 1024],
            ['key' => 'workflow.step.department-life.05.body', 'group' => '流程图节点', 'label' => '形式审查说明', 'default_value' => '对应旧流程“形式审查”，不通过则退回补正或驳回。', 'sort_order' => 1025],
            ['key' => 'workflow.step.department-life.07.title', 'group' => '流程图节点', 'label' => '立项启动标题', 'default_value' => '立项启动', 'sort_order' => 1026],
            ['key' => 'workflow.step.department-life.07.body', 'group' => '流程图节点', 'label' => '立项启动说明', 'default_value' => '立项结果确认、合同任务书启动和归档衔接。', 'sort_order' => 1027],
            ['key' => 'workflow.step.department-life.09.title', 'group' => '流程图节点', 'label' => '任务书审查标题', 'default_value' => '任务书审查', 'sort_order' => 1028],
            ['key' => 'workflow.step.department-life.09.body', 'group' => '流程图节点', 'label' => '任务书审查说明', 'default_value' => '任务书审核通过后作为立项后管理依据。', 'sort_order' => 1029],
            ['key' => 'workflow.step.department-life.13.title', 'group' => '流程图节点', 'label' => '验收复核标题', 'default_value' => '验收复核', 'sort_order' => 1030],
            ['key' => 'workflow.step.department-life.13.body', 'group' => '流程图节点', 'label' => '验收复核说明', 'default_value' => '验收业务复核后流转专家或管理员终审。', 'sort_order' => 1031],
            ['key' => 'workflow.step.department-life.15.title', 'group' => '流程图节点', 'label' => '归档管理标题', 'default_value' => '归档管理', 'sort_order' => 1032],
            ['key' => 'workflow.step.department-life.15.body', 'group' => '流程图节点', 'label' => '归档管理说明', 'default_value' => '验收关闭后项目归档，后续可补充成果登记。', 'sort_order' => 1033],
            ['key' => 'workflow.lane.expert-life.title', 'group' => '流程图节点', 'label' => '全生命周期-评审专家', 'default_value' => '评审专家', 'sort_order' => 1034],
            ['key' => 'workflow.lane.expert-life.owner', 'group' => '流程图节点', 'label' => '全生命周期-专家组', 'default_value' => '专家组', 'sort_order' => 1035],
            ['key' => 'workflow.step.expert-life.06.title', 'group' => '流程图节点', 'label' => '专家评审标题', 'default_value' => '专家评审', 'sort_order' => 1036],
            ['key' => 'workflow.step.expert-life.06.body', 'group' => '流程图节点', 'label' => '专家评审说明', 'default_value' => '项目评审评分推荐，形成评审意见。', 'sort_order' => 1037],
            ['key' => 'workflow.step.expert-life.13B.title', 'group' => '流程图节点', 'label' => '验收评审标题', 'default_value' => '验收评审', 'sort_order' => 1038],
            ['key' => 'workflow.step.expert-life.13B.body', 'group' => '流程图节点', 'label' => '验收评审说明', 'default_value' => '验收阶段形成评分和专家意见。', 'sort_order' => 1039],
            ['key' => 'workflow.step.expert-life.expert_pool.title', 'group' => '流程图节点', 'label' => '专家认证标题', 'default_value' => '专家认证', 'sort_order' => 1040],
            ['key' => 'workflow.step.expert-life.expert_pool.body', 'group' => '流程图节点', 'label' => '专家认证说明', 'default_value' => '专家提交专业方向和资质说明，管理员审核后沉淀为专家库资料。', 'sort_order' => 1041],
            ['key' => 'workflow.lane.leader-life.title', 'group' => '流程图节点', 'label' => '全生命周期-局领导/办公会', 'default_value' => '局领导/办公会', 'sort_order' => 1042],
            ['key' => 'workflow.lane.leader-life.owner', 'group' => '流程图节点', 'label' => '全生命周期-终审决策', 'default_value' => '终审决策', 'sort_order' => 1043],
            ['key' => 'workflow.step.leader-life.06B.title', 'group' => '流程图节点', 'label' => '办公会决策标题', 'default_value' => '办公会决策', 'sort_order' => 1044],
            ['key' => 'workflow.step.leader-life.06B.body', 'group' => '流程图节点', 'label' => '办公会决策说明', 'default_value' => '确定拟资助项目、经费安排和线下批复。', 'sort_order' => 1045],
            ['key' => 'workflow.step.leader-life.07B.title', 'group' => '流程图节点', 'label' => '管理员终审标题', 'default_value' => '管理员终审', 'sort_order' => 1046],
            ['key' => 'workflow.step.leader-life.07B.body', 'group' => '流程图节点', 'label' => '管理员终审说明', 'default_value' => '系统内记录终审通过、退回或驳回结果。', 'sort_order' => 1047],
            ['key' => 'workflow.step.leader-life.16.title', 'group' => '流程图节点', 'label' => '验收终审关闭标题', 'default_value' => '验收终审关闭', 'sort_order' => 1048],
            ['key' => 'workflow.step.leader-life.16.body', 'group' => '流程图节点', 'label' => '验收终审关闭说明', 'default_value' => '终审通过后关闭验收，项目完成归档。', 'sort_order' => 1049],

            ['key' => 'lifecycle.page.subtitle', 'group' => '全周期管理', 'label' => '页面副标题', 'default_value' => '合同任务书、项目实施进展、整改闭环和专家认证', 'sort_order' => 600],
            ['key' => 'lifecycle.filter.keyword', 'group' => '全周期管理', 'label' => '关键词占位', 'default_value' => '项目/单位/标题', 'sort_order' => 610],
            ['key' => 'lifecycle.filter.status', 'group' => '全周期管理', 'label' => '状态占位', 'default_value' => '状态', 'sort_order' => 620],
            ['key' => 'lifecycle.action.refresh', 'group' => '全周期管理', 'label' => '刷新按钮', 'default_value' => '刷新', 'sort_order' => 630],
            ['key' => 'lifecycle.task_books.tab', 'group' => '全周期管理', 'label' => '合同任务书 Tab', 'default_value' => '合同任务书', 'sort_order' => 640],
            ['key' => 'lifecycle.task_books.tip', 'group' => '全周期管理', 'label' => '合同任务书说明', 'default_value' => '单位填报任务书，管理员审核通过后作为立项后管理依据。', 'sort_order' => 650],
            ['key' => 'lifecycle.task_books.create', 'group' => '全周期管理', 'label' => '新增任务书按钮', 'default_value' => '新增任务书', 'sort_order' => 660],
            ['key' => 'lifecycle.progress.tab', 'group' => '全周期管理', 'label' => '实施进展 Tab', 'default_value' => '实施进展', 'sort_order' => 670],
            ['key' => 'lifecycle.progress.tip', 'group' => '全周期管理', 'label' => '实施进展说明', 'default_value' => '单位定期提交项目实施情况，管理员确认或退回补正。', 'sort_order' => 680],
            ['key' => 'lifecycle.progress.create', 'group' => '全周期管理', 'label' => '新增进展按钮', 'default_value' => '新增进展', 'sort_order' => 690],
            ['key' => 'lifecycle.rectifications.tab', 'group' => '全周期管理', 'label' => '整改闭环 Tab', 'default_value' => '整改闭环', 'sort_order' => 700],
            ['key' => 'lifecycle.rectifications.tip', 'group' => '全周期管理', 'label' => '整改闭环说明', 'default_value' => '管理员发起整改要求，单位提交整改说明，管理员审核闭环。', 'sort_order' => 710],
            ['key' => 'lifecycle.rectifications.create', 'group' => '全周期管理', 'label' => '发起整改按钮', 'default_value' => '发起整改', 'sort_order' => 720],
            ['key' => 'lifecycle.rectifications.submit_response', 'group' => '全周期管理', 'label' => '提交整改按钮', 'default_value' => '提交整改', 'sort_order' => 725],
            ['key' => 'lifecycle.certifications.tab', 'group' => '全周期管理', 'label' => '专家认证 Tab', 'default_value' => '专家认证', 'sort_order' => 730],
            ['key' => 'lifecycle.certifications.tip', 'group' => '全周期管理', 'label' => '专家认证说明', 'default_value' => '专家提交专业方向和资质说明，管理员审核后作为专家库基础信息。', 'sort_order' => 740],
            ['key' => 'lifecycle.certifications.create', 'group' => '全周期管理', 'label' => '提交认证按钮', 'default_value' => '提交认证', 'sort_order' => 750],
            ['key' => 'lifecycle.action.detail', 'group' => '全周期管理', 'label' => '详情按钮', 'default_value' => '详情', 'sort_order' => 760],
            ['key' => 'lifecycle.action.edit', 'group' => '全周期管理', 'label' => '编辑按钮', 'default_value' => '编辑', 'sort_order' => 770],
            ['key' => 'lifecycle.action.submit', 'group' => '全周期管理', 'label' => '提交按钮', 'default_value' => '提交', 'sort_order' => 780],
            ['key' => 'lifecycle.action.review', 'group' => '全周期管理', 'label' => '审核按钮', 'default_value' => '审核', 'sort_order' => 790],
            ['key' => 'lifecycle.column.project', 'group' => '全周期管理', 'label' => '项目列名', 'default_value' => '项目', 'sort_order' => 791],
            ['key' => 'lifecycle.column.unit', 'group' => '全周期管理', 'label' => '单位列名', 'default_value' => '单位', 'sort_order' => 792],
            ['key' => 'lifecycle.column.task_title', 'group' => '全周期管理', 'label' => '任务书标题列名', 'default_value' => '任务书标题', 'sort_order' => 793],
            ['key' => 'lifecycle.column.status', 'group' => '全周期管理', 'label' => '状态列名', 'default_value' => '状态', 'sort_order' => 794],
            ['key' => 'lifecycle.column.submitted_at', 'group' => '全周期管理', 'label' => '提交时间列名', 'default_value' => '提交时间', 'sort_order' => 795],
            ['key' => 'lifecycle.column.actions', 'group' => '全周期管理', 'label' => '操作列名', 'default_value' => '操作', 'sort_order' => 796],
            ['key' => 'lifecycle.column.period', 'group' => '全周期管理', 'label' => '周期列名', 'default_value' => '周期', 'sort_order' => 797],
            ['key' => 'lifecycle.column.progress_date', 'group' => '全周期管理', 'label' => '进展日期列名', 'default_value' => '进展日期', 'sort_order' => 798],
            ['key' => 'lifecycle.column.summary', 'group' => '全周期管理', 'label' => '进展摘要列名', 'default_value' => '进展摘要', 'sort_order' => 799],
            ['key' => 'lifecycle.column.rectification_title', 'group' => '全周期管理', 'label' => '整改事项列名', 'default_value' => '整改事项', 'sort_order' => 800],
            ['key' => 'lifecycle.column.due_date', 'group' => '全周期管理', 'label' => '截止日期列名', 'default_value' => '截止日期', 'sort_order' => 801],
            ['key' => 'lifecycle.column.expert_username', 'group' => '全周期管理', 'label' => '专家账号列名', 'default_value' => '专家账号', 'sort_order' => 802],
            ['key' => 'lifecycle.column.name', 'group' => '全周期管理', 'label' => '姓名列名', 'default_value' => '姓名', 'sort_order' => 803],
            ['key' => 'lifecycle.column.organization', 'group' => '全周期管理', 'label' => '单位机构列名', 'default_value' => '单位/机构', 'sort_order' => 804],
            ['key' => 'lifecycle.column.specialty', 'group' => '全周期管理', 'label' => '专业方向列名', 'default_value' => '专业方向', 'sort_order' => 805],
            ['key' => 'lifecycle.column.professional_title', 'group' => '全周期管理', 'label' => '职称列名', 'default_value' => '职称', 'sort_order' => 806],

            ['key' => 'migration.intro', 'group' => '迁移准备', 'label' => '迁移准备提示', 'default_value' => '迁移准备用于旧系统历史数据导入前体检：先备份旧库和 upload 附件，生成 dry-run 报告，处理缺失文件/字段映射/账号冲突后，再执行正式迁移。新系统日常使用不依赖这里。', 'sort_order' => 800],
            ['key' => 'settings.public_home.card_title', 'group' => '系统配置', 'label' => '首页内容卡片标题', 'default_value' => '首页内容', 'sort_order' => 900],
            ['key' => 'settings.public_home.card_body', 'group' => '系统配置', 'label' => '首页内容卡片说明', 'default_value' => '导航、公告、下载、服务事项和 logo/banner 请进入首页管理维护。', 'sort_order' => 910],
            ['key' => 'settings.public_home.button', 'group' => '系统配置', 'label' => '进入首页管理按钮', 'default_value' => '进入首页管理', 'sort_order' => 920],
            ['key' => 'public.toolbar.help', 'group' => '公开首页', 'label' => '顶部在线帮助', 'default_value' => '在线帮助', 'sort_order' => 930],
            ['key' => 'public.toolbar.sitemap', 'group' => '公开首页', 'label' => '顶部全站导航', 'default_value' => '全站导航', 'sort_order' => 931],
            ['key' => 'public.toolbar.warning', 'group' => '公开首页', 'label' => '顶部安全提示', 'default_value' => '本平台为互联网非涉密平台，请勿上传涉密资料', 'sort_order' => 932],
            ['key' => 'auth.login', 'group' => '登录注册', 'label' => '登录入口', 'default_value' => '登录', 'sort_order' => 940],
            ['key' => 'auth.forgot_password', 'group' => '登录注册', 'label' => '忘记密码入口', 'default_value' => '忘记密码', 'sort_order' => 941],
            ['key' => 'auth.register_unit', 'group' => '登录注册', 'label' => '新单位注册入口', 'default_value' => '新单位注册', 'sort_order' => 942],
            ['key' => 'project.action.detail', 'group' => '项目申报', 'label' => '详情按钮', 'default_value' => '详情', 'sort_order' => 950],
            ['key' => 'project.action.lifecycle', 'group' => '项目申报', 'label' => '全周期按钮', 'default_value' => '全周期', 'sort_order' => 951],
            ['key' => 'project.action.more', 'group' => '项目申报', 'label' => '更多按钮', 'default_value' => '更多', 'sort_order' => 952],
            ['key' => 'project.action.edit', 'group' => '项目申报', 'label' => '编辑按钮', 'default_value' => '编辑', 'sort_order' => 953],
            ['key' => 'project.action.files', 'group' => '项目申报', 'label' => '附件按钮', 'default_value' => '附件', 'sort_order' => 954],
            ['key' => 'project.action.submit', 'group' => '项目申报', 'label' => '提交按钮', 'default_value' => '提交', 'sort_order' => 955],
            ['key' => 'project.action.withdraw', 'group' => '项目申报', 'label' => '撤回按钮', 'default_value' => '撤回', 'sort_order' => 956],
            ['key' => 'project.action.extension', 'group' => '项目申报', 'label' => '申请延期按钮', 'default_value' => '申请延期', 'sort_order' => 957],
            ['key' => 'project.action.enter_acceptance', 'group' => '项目申报', 'label' => '进入验收按钮', 'default_value' => '进入验收', 'sort_order' => 958],
            ['key' => 'project.action.close', 'group' => '项目申报', 'label' => '关闭验收按钮', 'default_value' => '关闭验收', 'sort_order' => 959],
            ['key' => 'project.action.review_logs', 'group' => '项目申报', 'label' => '审核记录按钮', 'default_value' => '审核记录', 'sort_order' => 960],
            ['key' => 'project.action.operation_logs', 'group' => '项目申报', 'label' => '操作日志按钮', 'default_value' => '操作日志', 'sort_order' => 961],
            ['key' => 'project.action.delete', 'group' => '项目申报', 'label' => '删除按钮', 'default_value' => '删除', 'sort_order' => 962],
            ['key' => 'acceptance.tab.pending', 'group' => '验收管理', 'label' => '待处理 Tab', 'default_value' => '待处理', 'sort_order' => 970],
            ['key' => 'acceptance.tab.reviewed', 'group' => '验收管理', 'label' => '已处理 Tab', 'default_value' => '已处理', 'sort_order' => 971],
            ['key' => 'acceptance.tab.visible', 'group' => '验收管理', 'label' => '全部可见 Tab', 'default_value' => '全部可见', 'sort_order' => 972],
        ];
    }

    public static function defaults(): array
    {
        return collect(self::items())
            ->mapWithKeys(fn (array $item): array => [$item['key'] => $item['default_value']])
            ->all();
    }
}
